/**
 * DIRECTAURANTE POS CORE v0.1 - Persistent Storage Layer
 * File-backed persistent document store matching MongoDB BSON/JSON conventions.
 * All mutations persist atomically to disk.
 */

import fs from 'fs';
import path from 'path';
import {
  Restaurant,
  Table,
  TableSession,
  GuestSubaccount,
  Product,
  Order,
  OrderItem,
  Payment,
  CashShift,
  CashMovement,
  AuditLog,
  Allergy,
  Ingredient,
  RestaurantPluginConfig,
  Printer,
  PrinterRoutingRule,
  ImportJob,
  PrintJob,
  InventoryItem,
  InventoryMovement,
  InventoryCount,
  Recipe,
  Supplier,
  PurchaseOrder,
  PriceHistoryRecord,
  User,
  RestaurantMember,
  Role,
  Shift,
  MemberHistoryRecord,
  ALL_PERMISSIONS,
  CustomerProfile,
  CustomerAddress,
  LoyaltyAccount,
  LoyaltyTransaction,
  LoyaltyReward,
  Promotion,
  PromotionRedemptionRecord,
  Expense,
  FinancialMovement,
  RestaurantSettlement,
  DriverSettlement,
  Solution,
  CommercialPlan,
  Entitlement,
} from './types';

export interface DatabaseSchema {
  restaurants: Restaurant[];
  tables: Table[];
  table_sessions: TableSession[];
  guest_subaccounts: GuestSubaccount[];
  products: Product[];
  orders: Order[];
  order_items: OrderItem[];
  payments: Payment[];
  cash_shifts: CashShift[];
  cash_movements: CashMovement[];
  audit_logs: AuditLog[];
  allergies: Allergy[];
  ingredients: Ingredient[];
  restaurant_plugins: RestaurantPluginConfig[];
  printers: Printer[];
  printer_routing_rules: PrinterRoutingRule[];
  import_jobs: ImportJob[];
  print_jobs: PrintJob[];
  inventory_items: InventoryItem[];
  inventory_movements: InventoryMovement[];
  inventory_counts: InventoryCount[];
  recipes: Recipe[];
  suppliers: Supplier[];
  purchase_orders: PurchaseOrder[];
  price_history: PriceHistoryRecord[];
  users: User[];
  restaurant_members: RestaurantMember[];
  roles: Role[];
  shifts: Shift[];
  member_history: MemberHistoryRecord[];
  customers: CustomerProfile[];
  loyalty_accounts: LoyaltyAccount[];
  loyalty_transactions: LoyaltyTransaction[];
  loyalty_rewards: LoyaltyReward[];
  promotions: Promotion[];
  promotion_redemptions: PromotionRedemptionRecord[];
  expenses: Expense[];
  financial_movements: FinancialMovement[];
  restaurant_settlements: RestaurantSettlement[];
  driver_settlements: DriverSettlement[];
  solutions: Solution[];
  commercial_plans: CommercialPlan[];
  entitlements: Entitlement[];
}

const DATA_DIR = path.resolve(process.cwd(), 'data');
const DATA_FILE = path.join(DATA_DIR, 'directaurante_store.json');
const INITIAL_RESTAURANT_ID = 'rest_directaurante_01';

export function getDefaultSeedData(): DatabaseSchema {
  const now = new Date().toISOString();

  const ingredients: Ingredient[] = [
    { id: 'ing_cacahuate', name: 'Cacahuate / Maní', category: 'Frutos secos' },
    { id: 'ing_nuez', name: 'Nueces', category: 'Frutos secos' },
    { id: 'ing_gluten', name: 'Gluten / Trigo', category: 'Cereales' },
    { id: 'ing_lacteos', name: 'Lácteos / Queso', category: 'Lácteos' },
    { id: 'ing_mariscos', name: 'Mariscos / Camarón', category: 'Pescados y Mariscos' },
    { id: 'ing_huevo', name: 'Huevo', category: 'Aves' },
    { id: 'ing_soya', name: 'Soya', category: 'Legumbres' },
    { id: 'ing_pollo', name: 'Pechuga de Pollo', category: 'Carnes' },
    { id: 'ing_res', name: 'Carne de Res 100% Angus', category: 'Carnes' },
    { id: 'ing_bbq', name: 'Salsa BBQ Ahumada', category: 'Salsas' },
  ];

  const allergies: Allergy[] = [
    {
      id: 'alg_cacahuate',
      name: 'Alergia Grave a Cacahuate y Frutos Secos',
      ingredient_ids: ['ing_cacahuate', 'ing_nuez'],
      severity: 'severe',
      description: 'Anafilaxia potencial. Requiere exclusión estricta de trazas.',
    },
    {
      id: 'alg_gluten',
      name: 'Intolerancia al Gluten / Celíaco',
      ingredient_ids: ['ing_gluten'],
      severity: 'moderate',
      description: 'Requiere preparación en área libre de harinas.',
    },
    {
      id: 'alg_mariscos',
      name: 'Alergia a Mariscos',
      ingredient_ids: ['ing_mariscos'],
      severity: 'severe',
      description: 'Reacción alérgica aguda.',
    },
    {
      id: 'alg_lacteos',
      name: 'Intolerancia a Lácteos',
      ingredient_ids: ['ing_lacteos'],
      severity: 'mild',
      description: 'Sin queso ni crema.',
    },
  ];

  const products: Product[] = [
    {
      id: 'prod_boneless_bbq',
      restaurant_id: INITIAL_RESTAURANT_ID,
      name: 'Boneless BBQ',
      category: 'Entradas',
      description: 'Trozos crujientes de pechuga de pollo bañados en salsa BBQ ahumada con aderezo ranch.',
      price_cents: 14000, // $140.00 MXN
      ingredient_ids: ['ing_pollo', 'ing_bbq', 'ing_gluten', 'ing_lacteos'],
      destination_station: 'kitchen',
      preparation_time_minutes: 15,
      target_preparation_seconds: 900, // 15 minutos SLA
      available_modifiers: ['Salsa aparte', 'Extra aderezo ranch', 'Poco picante', 'Bien dorados'],
      available: true,
    },
    {
      id: 'prod_cerveza',
      restaurant_id: INITIAL_RESTAURANT_ID,
      name: 'Cerveza Nacional Ultra',
      category: 'Bebidas',
      description: 'Cerveza clara bien fría de 355 ml.',
      price_cents: 4500, // $45.00 MXN
      ingredient_ids: ['ing_gluten'],
      destination_station: 'bar',
      preparation_time_minutes: 2,
      target_preparation_seconds: 120, // 2 minutos SLA
      available_modifiers: ['Vaso frío', 'Con limón y sal', 'Sin vaso'],
      inventory_item_id: 'inv_cerveza_ultra',
      available: true,
    },
    {
      id: 'prod_hamburguesa',
      restaurant_id: INITIAL_RESTAURANT_ID,
      name: 'Hamburguesa Clásica Angus',
      category: 'Platillos',
      description: '200g de carne de res Angus, queso cheddar fundido, lechuga, jitomate y pan brioche.',
      price_cents: 15000, // $150.00 MXN
      ingredient_ids: ['ing_res', 'ing_gluten', 'ing_lacteos'],
      destination_station: 'kitchen',
      preparation_time_minutes: 15,
      target_preparation_seconds: 900,
      available_modifiers: ['+ Tocino', '- Cebolla', 'Salsa aparte', 'Término medio', 'Bien cocida', 'Sin jitomate'],
      available: true,
    },
    {
      id: 'prod_burritos',
      restaurant_id: INITIAL_RESTAURANT_ID,
      name: 'Burritos Norteños de Res',
      category: 'Platillos',
      description: 'Tortilla de harina rellena de carne asada con frijoles refritos y queso asadero.',
      price_cents: 11000, // $110.00 MXN cada uno
      ingredient_ids: ['ing_res', 'ing_gluten', 'ing_lacteos'],
      destination_station: 'kitchen',
      preparation_time_minutes: 12,
      target_preparation_seconds: 720, // 12 minutos SLA
      available_modifiers: ['Sin cebolla', 'Salsa verde aparte', 'Cortar a la mitad', 'Extra queso'],
      available: true,
    },
    {
      id: 'prod_michelada',
      restaurant_id: INITIAL_RESTAURANT_ID,
      name: 'Michelada Especial',
      category: 'Bebidas',
      description: 'Vaso escarchado con limón, sal, salsas negras de la casa y clamato preparado.',
      price_cents: 9000, // $90.00 MXN
      ingredient_ids: ['ing_gluten', 'ing_soya'],
      destination_station: 'bar',
      preparation_time_minutes: 4,
      target_preparation_seconds: 240,
      available_modifiers: ['Poco picante', 'Sin clamato', 'Extra limón', 'Escarchado con tajín'],
      available: true,
    },
    {
      id: 'prod_ensalada',
      restaurant_id: INITIAL_RESTAURANT_ID,
      name: 'Ensalada César con Pollo',
      category: 'Platillos',
      description: 'Lechuga orejona fresca, pechuga a la plancha, crutones dorados y queso parmesano.',
      price_cents: 13500, // $135.00 MXN
      ingredient_ids: ['ing_pollo', 'ing_lacteos', 'ing_gluten'],
      destination_station: 'kitchen',
      preparation_time_minutes: 8,
      target_preparation_seconds: 480,
      available_modifiers: ['Aderezo aparte', 'Sin crutones', 'Pechuga bien dorada'],
      available: true,
    },
    {
      id: 'prod_papas',
      restaurant_id: INITIAL_RESTAURANT_ID,
      name: 'Papas a la Francesa Crujientes',
      category: 'Snacks',
      description: 'Papas corte delgado sazonadas con paprika y sal de mar.',
      price_cents: 6000, // $60.00 MXN
      ingredient_ids: [],
      destination_station: 'kitchen',
      preparation_time_minutes: 8,
      inventory_item_id: 'inv_papas_francesa',
      available: true,
    },
    {
      id: 'prod_agua',
      restaurant_id: INITIAL_RESTAURANT_ID,
      name: 'Agua Embotellada 600ml',
      category: 'Bebidas',
      description: 'Agua purificada natural de manantial.',
      price_cents: 3500, // $35.00 MXN
      ingredient_ids: [],
      destination_station: 'bar',
      preparation_time_minutes: 1,
      inventory_item_id: 'inv_agua_600',
      available: true,
    },
    {
      id: 'prod_brownie',
      restaurant_id: INITIAL_RESTAURANT_ID,
      name: 'Brownie de Chocolate y Cacahuate',
      category: 'Postres',
      description: 'Brownie tibio con nueces y trocitos de cacahuate tostado servido con helado.',
      price_cents: 8500, // $85.00 MXN
      ingredient_ids: ['ing_cacahuate', 'ing_nuez', 'ing_gluten', 'ing_lacteos', 'ing_huevo'],
      destination_station: 'kitchen',
      preparation_time_minutes: 6,
      inventory_item_id: 'inv_brownie_porc',
      available: true,
    },
  ];

  const restaurants: Restaurant[] = [
    {
      id: INITIAL_RESTAURANT_ID,
      name: 'Directaurante Grill & Bar',
      legal_name: 'Directaurante Operadora Gastronómica S.A.P.I. de C.V.',
      currency: 'MXN',
      tax_rate: 0.16,
      created_at: now,
    },
  ];

  const tables: Table[] = [
    { id: 'tbl_1', restaurant_id: INITIAL_RESTAURANT_ID, number: 'Mesa 1', capacity: 4, status: 'available' },
    { id: 'tbl_2', restaurant_id: INITIAL_RESTAURANT_ID, number: 'Mesa 2', capacity: 2, status: 'available' },
    { id: 'tbl_3', restaurant_id: INITIAL_RESTAURANT_ID, number: 'Mesa 3', capacity: 6, status: 'available' },
    { id: 'tbl_4', restaurant_id: INITIAL_RESTAURANT_ID, number: 'Mesa 4', capacity: 4, status: 'available' },
    { id: 'tbl_5', restaurant_id: INITIAL_RESTAURANT_ID, number: 'Mesa 5', capacity: 8, status: 'available' },
    { id: 'tbl_6', restaurant_id: INITIAL_RESTAURANT_ID, number: 'Mesa 6 (Terraza)', capacity: 4, status: 'available' },
    { id: 'tbl_7', restaurant_id: INITIAL_RESTAURANT_ID, number: 'Mesa 7 (Terraza)', capacity: 4, status: 'available' },
    { id: 'tbl_8', restaurant_id: INITIAL_RESTAURANT_ID, number: 'Barra 1', capacity: 3, status: 'available' },
  ];

  const restaurant_plugins: RestaurantPluginConfig[] = [
    { restaurant_id: INITIAL_RESTAURANT_ID, plugin_id: 'pos', enabled: true, version: '0.1.0', settings: {}, updated_at: now },
    { restaurant_id: INITIAL_RESTAURANT_ID, plugin_id: 'kds', enabled: true, version: '0.1.0', settings: { sound_alerts: true }, updated_at: now },
    { restaurant_id: INITIAL_RESTAURANT_ID, plugin_id: 'cash', enabled: true, version: '0.1.0', settings: { strict_count: true }, updated_at: now },
    { restaurant_id: INITIAL_RESTAURANT_ID, plugin_id: 'directprint', enabled: true, version: '0.1.0', settings: { auto_ticket: true }, updated_at: now },
    { restaurant_id: INITIAL_RESTAURANT_ID, plugin_id: 'directimport', enabled: true, version: '0.1.0', settings: {}, updated_at: now },
    { restaurant_id: INITIAL_RESTAURANT_ID, plugin_id: 'inventory', enabled: false, version: '0.1.0', settings: {}, updated_at: now },
    { restaurant_id: INITIAL_RESTAURANT_ID, plugin_id: 'loyalty', enabled: false, version: '0.1.0', settings: {}, updated_at: now },
    { restaurant_id: INITIAL_RESTAURANT_ID, plugin_id: 'ai', enabled: false, version: '0.1.0', settings: {}, updated_at: now },
  ];

  const cash_shifts: CashShift[] = [
    {
      id: 'shift_init_01',
      restaurant_id: INITIAL_RESTAURANT_ID,
      opened_by: 'Cajero Principal (Admin)',
      opened_at: now,
      initial_float_cents: 200000, // $2,000.00 MXN fondo inicial
      status: 'open',
      expected_cash_cents: 200000,
      notes: 'Turno matutino abierto con fondo estándar.',
    },
  ];

  const cash_movements: CashMovement[] = [
    {
      id: 'mov_init_01',
      shift_id: 'shift_init_01',
      restaurant_id: INITIAL_RESTAURANT_ID,
      type: 'opening_float',
      amount_cents: 200000,
      description: 'Fondo de apertura de caja',
      performed_by: 'Cajero Principal',
      timestamp: now,
    },
  ];

  const printers: Printer[] = [
    {
      id: 'prn_kitchen_01',
      restaurant_id: INITIAL_RESTAURANT_ID,
      name: 'Comandera Cocina Caliente (ESC/POS)',
      connection_type: 'ethernet',
      host: '192.168.1.201',
      address: '192.168.1.201',
      port: 9100,
      station: 'kitchen',
      paper_width: 80,
      protocol: 'esc_pos',
      is_active: true,
      enabled: true,
    },
    {
      id: 'prn_bar_01',
      restaurant_id: INITIAL_RESTAURANT_ID,
      name: 'Comandera Barra y Coctelería',
      connection_type: 'ethernet',
      host: '192.168.1.202',
      address: '192.168.1.202',
      port: 9100,
      station: 'bar',
      paper_width: 80,
      protocol: 'esc_pos',
      is_active: true,
      enabled: true,
    },
    {
      id: 'prn_cashier_01',
      restaurant_id: INITIAL_RESTAURANT_ID,
      name: 'Impresora de Cuentas y Tickets Caja',
      connection_type: 'usb',
      host: '/dev/usb/lp0',
      address: '/dev/usb/lp0',
      port: 0,
      station: 'cashier',
      paper_width: 80,
      protocol: 'esc_pos',
      is_active: true,
      enabled: true,
    },
  ];

  const printer_routing_rules: PrinterRoutingRule[] = [
    {
      id: 'rule_kitchen',
      restaurant_id: INITIAL_RESTAURANT_ID,
      station: 'kitchen',
      printer_id: 'prn_kitchen_01',
      categories: ['Platillos', 'Entradas', 'Postres', 'Snacks'],
    },
    {
      id: 'rule_bar',
      restaurant_id: INITIAL_RESTAURANT_ID,
      station: 'bar',
      printer_id: 'prn_bar_01',
      categories: ['Bebidas'],
    },
  ];

  const inventory_items: InventoryItem[] = [
    {
      id: 'inv_pan_burger',
      restaurant_id: INITIAL_RESTAURANT_ID,
      sku: 'INS-PAN-01',
      name: 'Pan Brioche Artesanal',
      category: 'Insumos Cocina',
      current_stock: 45,
      min_stock: 20,
      max_stock: 100,
      base_unit: 'pza',
      purchase_unit: 'caja',
      conversion_factor: 24,
      cost_cents: 800, // $8.00 MXN
      allow_negative_stock: false,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'inv_carne_angus',
      restaurant_id: INITIAL_RESTAURANT_ID,
      sku: 'INS-CAR-01',
      name: 'Carne Molida Angus 80/20',
      category: 'Carnes & Proteínas',
      current_stock: 15.5,
      min_stock: 5.0,
      max_stock: 40.0,
      base_unit: 'kg',
      cost_cents: 18000, // $180.00 MXN/kg
      allow_negative_stock: false,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'inv_pechuga_pollo',
      restaurant_id: INITIAL_RESTAURANT_ID,
      sku: 'INS-POL-01',
      name: 'Pechuga de Pollo en Cubos',
      category: 'Carnes & Proteínas',
      current_stock: 12.0,
      min_stock: 4.0,
      max_stock: 30.0,
      base_unit: 'kg',
      cost_cents: 11000,
      allow_negative_stock: false,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'inv_cerveza_ultra',
      restaurant_id: INITIAL_RESTAURANT_ID,
      sku: 'BEB-CER-01',
      name: 'Cerveza Nacional Ultra 355ml',
      category: 'Bebidas & Licores',
      current_stock: 48,
      min_stock: 24,
      max_stock: 120,
      base_unit: 'pza',
      purchase_unit: 'caja',
      conversion_factor: 24,
      cost_cents: 2200, // $22.00 MXN
      linked_product_id: 'prod_cerveza',
      allow_negative_stock: false,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'inv_agua_600',
      restaurant_id: INITIAL_RESTAURANT_ID,
      sku: 'BEB-AGU-01',
      name: 'Agua Purificada 600ml',
      category: 'Bebidas & Licores',
      current_stock: 6, // Low stock: min 12
      min_stock: 12,
      max_stock: 60,
      base_unit: 'pza',
      purchase_unit: 'caja',
      conversion_factor: 12,
      cost_cents: 1200,
      linked_product_id: 'prod_agua',
      allow_negative_stock: false,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'inv_brownie_porc',
      restaurant_id: INITIAL_RESTAURANT_ID,
      sku: 'POS-BRO-01',
      name: 'Porción Brownie Chocolate',
      category: 'Insumos Cocina',
      current_stock: 0, // Out of stock
      min_stock: 6,
      max_stock: 24,
      base_unit: 'pza',
      cost_cents: 3500,
      linked_product_id: 'prod_brownie',
      allow_negative_stock: false,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'inv_queso_cheddar',
      restaurant_id: INITIAL_RESTAURANT_ID,
      sku: 'LAC-CHE-01',
      name: 'Queso Cheddar Rebanado',
      category: 'Lácteos',
      current_stock: 60,
      min_stock: 20,
      max_stock: 150,
      base_unit: 'pza',
      cost_cents: 350,
      allow_negative_stock: false,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'inv_salsa_bbq',
      restaurant_id: INITIAL_RESTAURANT_ID,
      sku: 'ABA-BBQ-01',
      name: 'Salsa BBQ Ahumada Artesanal',
      category: 'Abarrotes',
      current_stock: 8.5,
      min_stock: 3.0,
      max_stock: 25.0,
      base_unit: 'lt',
      cost_cents: 6500,
      allow_negative_stock: false,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'inv_papas_francesa',
      restaurant_id: INITIAL_RESTAURANT_ID,
      sku: 'INS-PAP-01',
      name: 'Papas Corte Delgado Congeladas',
      category: 'Insumos Cocina',
      current_stock: 25.0,
      min_stock: 8.0,
      max_stock: 60.0,
      base_unit: 'kg',
      cost_cents: 4000, // $40.00 MXN/kg
      linked_product_id: 'prod_papas',
      allow_negative_stock: false,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'inv_tocino_rebanada',
      restaurant_id: INITIAL_RESTAURANT_ID,
      sku: 'CAR-TOC-01',
      name: 'Tocino Ahumado Rebanado',
      category: 'Carnes & Proteínas',
      current_stock: 80,
      min_stock: 20,
      max_stock: 200,
      base_unit: 'pza',
      cost_cents: 500, // $5.00 MXN/pza
      allow_negative_stock: false,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
  ];

  const inventory_movements: InventoryMovement[] = [
    {
      id: 'mov_inv_init_01',
      restaurant_id: INITIAL_RESTAURANT_ID,
      inventory_item_id: 'inv_pan_burger',
      item_name: 'Pan Brioche Artesanal',
      movement_type: 'initial_stock',
      quantity: 45,
      unit: 'pza',
      previous_stock: 0,
      new_stock: 45,
      reason: 'Inventario inicial del sistema',
      reference_type: 'initial',
      reference_id: 'INIT-2026',
      user_id: 'Admin Inventario',
      cost_cents_per_unit: 800,
      created_at: now,
    },
    {
      id: 'mov_inv_init_02',
      restaurant_id: INITIAL_RESTAURANT_ID,
      inventory_item_id: 'inv_cerveza_ultra',
      item_name: 'Cerveza Nacional Ultra 355ml',
      movement_type: 'purchase',
      quantity: 48,
      unit: 'pza',
      previous_stock: 0,
      new_stock: 48,
      reason: 'Compra inicial factura F-4491',
      reference_type: 'purchase',
      reference_id: 'FAC-4491',
      user_id: 'Admin Compras',
      cost_cents_per_unit: 2200,
      created_at: now,
    },
    {
      id: 'mov_inv_init_03',
      restaurant_id: INITIAL_RESTAURANT_ID,
      inventory_item_id: 'inv_agua_600',
      item_name: 'Agua Purificada 600ml',
      movement_type: 'initial_stock',
      quantity: 6,
      unit: 'pza',
      previous_stock: 0,
      new_stock: 6,
      reason: 'Inventario inicial',
      reference_type: 'initial',
      reference_id: 'INIT-2026',
      user_id: 'Admin Inventario',
      cost_cents_per_unit: 1200,
      created_at: now,
    },
  ];

  return {
    restaurants,
    tables,
    table_sessions: [],
    guest_subaccounts: [],
    products,
    orders: [],
    order_items: [],
    payments: [],
    cash_shifts,
    cash_movements,
    audit_logs: [
      {
        id: `aud_init_${Date.now()}`,
        restaurant_id: INITIAL_RESTAURANT_ID,
        action: 'system_initialized',
        entity_type: 'plugin',
        entity_id: 'pos',
        actor: 'Directaurante Core System',
        notes: 'Arranque del módulo POS Core v0.1 con datos operacionales reales.',
        timestamp: now,
      },
    ],
    allergies,
    ingredients,
    restaurant_plugins,
    printers,
    printer_routing_rules,
    import_jobs: [],
    print_jobs: [],
    inventory_items,
    inventory_movements,
    inventory_counts: [],
    recipes: [
      {
        id: 'rec_hamburguesa',
        restaurant_id: INITIAL_RESTAURANT_ID,
        product_id: 'prod_hamburguesa',
        name: 'Hamburguesa Clásica Angus',
        yield_quantity: 1,
        yield_unit: 'porción',
        items: [
          {
            inventory_item_id: 'inv_pan_burger',
            item_name: 'Pan Brioche Artesanal',
            quantity: 1,
            unit: 'pza',
            waste_percent: 0,
            notes: 'Pan brioche dorado',
          },
          {
            inventory_item_id: 'inv_carne_angus',
            item_name: 'Carne Molida Angus 80/20',
            quantity: 0.15,
            unit: 'kg',
            waste_percent: 5,
            notes: 'Porción 150g carne',
          },
          {
            inventory_item_id: 'inv_queso_cheddar',
            item_name: 'Queso Cheddar Rebanado',
            quantity: 1,
            unit: 'pza',
            waste_percent: 0,
            notes: '1 rebanada fundida',
          },
          {
            inventory_item_id: 'inv_salsa_bbq',
            item_name: 'Salsa BBQ Ahumada Artesanal',
            quantity: 0.02,
            unit: 'lt',
            waste_percent: 2,
            notes: '20 ml aderezo base',
          },
        ],
        modifier_items: [
          {
            modifier_name: '+ Tocino',
            affects_inventory: true,
            inventory_item_id: 'inv_tocino_rebanada',
            quantity: 2,
            unit: 'pza',
            waste_percent: 0,
            notes: '2 tiras de tocino crujiente',
          },
          {
            modifier_name: '- Cebolla',
            affects_inventory: false,
            notes: 'Exclusión sin consumo',
          },
          {
            modifier_name: 'Salsa aparte',
            affects_inventory: false,
          },
          {
            modifier_name: 'Término medio',
            affects_inventory: false,
          },
          {
            modifier_name: 'Bien cocida',
            affects_inventory: false,
          },
          {
            modifier_name: 'Sin jitomate',
            affects_inventory: false,
          },
        ],
        version: 1,
        is_active: true,
        preparation_instructions:
          'Sellar la carne a la plancha por 3 minutos por lado. Colocar queso para fundir. Montar en pan brioche con salsa.',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'rec_burritos',
        restaurant_id: INITIAL_RESTAURANT_ID,
        product_id: 'prod_burritos',
        name: 'Burritos Norteños de Res',
        yield_quantity: 1,
        yield_unit: 'porción',
        items: [
          {
            inventory_item_id: 'inv_carne_angus',
            item_name: 'Carne Molida Angus 80/20',
            quantity: 0.18,
            unit: 'kg',
            waste_percent: 5,
          },
          {
            inventory_item_id: 'inv_queso_cheddar',
            item_name: 'Queso Cheddar Rebanado',
            quantity: 1,
            unit: 'pza',
            waste_percent: 0,
          },
          {
            inventory_item_id: 'inv_salsa_bbq',
            item_name: 'Salsa BBQ Ahumada Artesanal',
            quantity: 0.03,
            unit: 'lt',
            waste_percent: 2,
          },
        ],
        modifier_items: [
          {
            modifier_name: 'Extra queso',
            affects_inventory: true,
            inventory_item_id: 'inv_queso_cheddar',
            quantity: 1,
            unit: 'pza',
          },
          {
            modifier_name: 'Sin cebolla',
            affects_inventory: false,
          },
          {
            modifier_name: 'Cortar a la mitad',
            affects_inventory: false,
          },
        ],
        version: 1,
        is_active: true,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'rec_ensalada',
        restaurant_id: INITIAL_RESTAURANT_ID,
        product_id: 'prod_ensalada',
        name: 'Ensalada César con Pollo',
        yield_quantity: 1,
        yield_unit: 'porción',
        items: [
          {
            inventory_item_id: 'inv_pechuga_pollo',
            item_name: 'Pechuga de Pollo en Cubos',
            quantity: 0.16,
            unit: 'kg',
            waste_percent: 4,
          },
          {
            inventory_item_id: 'inv_queso_cheddar',
            item_name: 'Queso Cheddar Rebanado',
            quantity: 1,
            unit: 'pza',
            waste_percent: 0,
          },
        ],
        version: 1,
        is_active: true,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'rec_papas',
        restaurant_id: INITIAL_RESTAURANT_ID,
        product_id: 'prod_papas',
        name: 'Papas a la Francesa Crujientes',
        yield_quantity: 1,
        yield_unit: 'porción',
        items: [
          {
            inventory_item_id: 'inv_papas_francesa',
            item_name: 'Papas Corte Delgado Congeladas',
            quantity: 0.25,
            unit: 'kg',
            waste_percent: 3,
          },
        ],
        version: 1,
        is_active: true,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'rec_salsa_bbq_sub',
        restaurant_id: INITIAL_RESTAURANT_ID,
        product_id: 'sub_salsa_bbq',
        name: 'Subreceta: Salsa BBQ Ahumada Artesanal Preparada',
        yield_quantity: 1000,
        yield_unit: 'ml',
        items: [
          {
            inventory_item_id: 'inv_salsa_bbq',
            item_name: 'Salsa BBQ Ahumada Artesanal',
            quantity: 1,
            unit: 'lt',
            waste_percent: 0,
          },
        ],
        version: 1,
        is_active: true,
        created_at: now,
        updated_at: now,
      },
    ],
    suppliers: [
      {
        id: 'sup_carnes_norte',
        restaurant_id: INITIAL_RESTAURANT_ID,
        name: 'Distribuidora Carnes del Norte S.A. de C.V.',
        legal_name: 'Carnes Finas del Norte S.A. de C.V.',
        phone: '+52 81 8345 6789',
        email: 'ventas@carnesdelnorte.mx',
        address: 'Av. Industrial 450, Monterrey, NL',
        tax_id: 'CDN980312AB1',
        notes: 'Proveedor principal de carne de res y tocino. Entregas martes y viernes.',
        is_active: true,
        created_at: now,
        updated_at: now,
        products: [
          {
            inventory_item_id: 'inv_carne_angus',
            item_name: 'Carne Molida Angus 80/20',
            supplier_sku: 'PROV-CR-01',
            purchase_unit: 'kg',
            conversion_factor: 1,
            last_purchase_cost_cents: 18000,
            is_preferred: true,
          },
          {
            inventory_item_id: 'inv_tocino_rebanada',
            item_name: 'Tocino Ahumado Rebanado',
            supplier_sku: 'PROV-TOC-02',
            purchase_unit: 'kg',
            conversion_factor: 1,
            last_purchase_cost_cents: 22000,
            is_preferred: true,
          },
        ],
      },
      {
        id: 'sup_panaderia_artesanal',
        restaurant_id: INITIAL_RESTAURANT_ID,
        name: 'Panadería Artesanal San Juan',
        legal_name: 'Panificadora San Juan S. de R.L.',
        phone: '+52 55 5567 1234',
        email: 'pedidos@panaderiasanjuan.com',
        address: 'Calle Panaderos 12, CDMX',
        tax_id: 'PSJ050720XYZ',
        notes: 'Pan brioche fresco diario. Se compra en cajas de 24 piezas.',
        is_active: true,
        created_at: now,
        updated_at: now,
        products: [
          {
            inventory_item_id: 'inv_pan_burger',
            item_name: 'Pan Brioche para Hamburguesa',
            supplier_sku: 'PAN-BRI-24',
            purchase_unit: 'caja',
            conversion_factor: 24,
            last_purchase_cost_cents: 19200,
            is_preferred: true,
          },
        ],
      },
      {
        id: 'sup_central_abastos',
        restaurant_id: INITIAL_RESTAURANT_ID,
        name: 'Central de Abarrotes y Verduras Don Pepe',
        legal_name: 'Comercializadora Agroalimentaria Pepe S.A.',
        phone: '+52 55 5600 9876',
        email: 'contacto@abastosdonpepe.com',
        address: 'Bodega 14-B Central de Abastos, Iztapalapa',
        tax_id: 'CAP120101M44',
        notes: 'Proveedor de abarrotes, aderezos, pollo y vegetales.',
        is_active: true,
        created_at: now,
        updated_at: now,
        products: [
          {
            inventory_item_id: 'inv_pechuga_pollo',
            item_name: 'Pechuga de Pollo en Cubos',
            supplier_sku: 'POL-PECH-01',
            purchase_unit: 'kg',
            conversion_factor: 1,
            last_purchase_cost_cents: 13000,
            is_preferred: true,
          },
          {
            inventory_item_id: 'inv_queso_cheddar',
            item_name: 'Queso Cheddar Rebanado',
            supplier_sku: 'LAC-CHED-01',
            purchase_unit: 'pza',
            conversion_factor: 1,
            last_purchase_cost_cents: 350,
            is_preferred: true,
          },
          {
            inventory_item_id: 'inv_papas_francesa',
            item_name: 'Papas Corte Delgado Congeladas',
            supplier_sku: 'PAP-FRAN-CONG',
            purchase_unit: 'kg',
            conversion_factor: 1,
            last_purchase_cost_cents: 4500,
            is_preferred: true,
          },
          {
            inventory_item_id: 'inv_salsa_bbq',
            item_name: 'Salsa BBQ Ahumada Artesanal',
            supplier_sku: 'SAL-BBQ-GAL',
            purchase_unit: 'lt',
            conversion_factor: 1,
            last_purchase_cost_cents: 9500,
            is_preferred: true,
          },
        ],
      },
      {
        id: 'sup_cerveceria_modelo',
        restaurant_id: INITIAL_RESTAURANT_ID,
        name: 'Distribuidora de Bebidas y Licores Modelo',
        legal_name: 'Bebidas del Centro S.A. de C.V.',
        phone: '+52 55 5234 5678',
        email: 'ordenes@bebidasmodelo.mx',
        address: 'Calzada México Tacuba 200, CDMX',
        tax_id: 'BCM950415QR8',
        notes: 'Cerveza y bebidas embotelladas. Pedidos con 48 hrs de anticipación.',
        is_active: true,
        created_at: now,
        updated_at: now,
        products: [
          {
            inventory_item_id: 'inv_cerveza_ultra',
            item_name: 'Cerveza Clara Ultra 355 ml',
            supplier_sku: 'CERV-ULT-24',
            purchase_unit: 'caja',
            conversion_factor: 24,
            last_purchase_cost_cents: 48000,
            is_preferred: true,
          },
          {
            inventory_item_id: 'inv_agua_600',
            item_name: 'Agua Natural Purificada 600 ml',
            supplier_sku: 'AGU-NAT-24',
            purchase_unit: 'caja',
            conversion_factor: 24,
            last_purchase_cost_cents: 21600,
            is_preferred: true,
          },
        ],
      },
    ],
    purchase_orders: [
      {
        id: 'po_000101',
        restaurant_id: INITIAL_RESTAURANT_ID,
        order_number: 'OC-000101',
        supplier_id: 'sup_carnes_norte',
        supplier_name: 'Distribuidora Carnes del Norte S.A. de C.V.',
        status: 'ordered',
        items: [
          {
            id: 'poi_101_1',
            inventory_item_id: 'inv_carne_angus',
            item_name: 'Carne Molida Angus 80/20',
            sku: 'PROV-CR-01',
            quantity_ordered: 10,
            quantity_received: 0,
            unit: 'kg',
            cost_cents_per_unit: 18000,
            total_cost_cents: 180000,
            notes: 'Corte fresco para hamburguesas',
          },
          {
            id: 'poi_101_2',
            inventory_item_id: 'inv_tocino_rebanada',
            item_name: 'Tocino Ahumado Rebanado',
            sku: 'PROV-TOC-02',
            quantity_ordered: 5,
            quantity_received: 0,
            unit: 'kg',
            cost_cents_per_unit: 22000,
            total_cost_cents: 110000,
          },
        ],
        subtotal_cents: 290000,
        tax_cents: 0,
        total_cents: 290000,
        payment_status: 'pending',
        paid_amount_cents: 0,
        due_date: new Date(Date.now() + 15 * 86400000).toISOString(),
        notes: 'Entrega programada para el turno matutino.',
        ordered_at: now,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'po_000100',
        restaurant_id: INITIAL_RESTAURANT_ID,
        order_number: 'OC-000100',
        supplier_id: 'sup_panaderia_artesanal',
        supplier_name: 'Panadería Artesanal San Juan',
        status: 'partially_received',
        items: [
          {
            id: 'poi_100_1',
            inventory_item_id: 'inv_pan_burger',
            item_name: 'Pan Brioche para Hamburguesa',
            sku: 'PAN-BRI-24',
            quantity_ordered: 10,
            quantity_received: 6,
            unit: 'caja',
            cost_cents_per_unit: 19200,
            total_cost_cents: 192000,
            notes: '10 cajas de 24 pzas cada una',
          },
        ],
        subtotal_cents: 192000,
        tax_cents: 0,
        total_cents: 192000,
        receipts: [
          {
            id: 'rec_seed_100_1',
            restaurant_id: INITIAL_RESTAURANT_ID,
            purchase_order_id: 'po_000100',
            receipt_number: 'REC-00001',
            invoice_number: 'FAC-48291',
            invoice_date: now,
            received_by: 'Almacén Central',
            received_at: now,
            items: [
              {
                purchase_order_item_id: 'poi_100_1',
                inventory_item_id: 'inv_pan_burger',
                item_name: 'Pan Brioche para Hamburguesa',
                quantity_received: 6,
                quantity_accepted: 6,
                quantity_rejected: 0,
                unit: 'caja',
                cost_cents_per_unit: 19200,
                conversion_factor: 24,
                base_unit: 'pza',
              },
            ],
            subtotal_cents: 115200,
            tax_cents: 0,
            total_cents: 115200,
            notes: 'Primera entrega de 6 cajas recibida en buen estado.',
          },
        ],
        payment_status: 'partially_paid',
        paid_amount_cents: 115200,
        due_date: new Date(Date.now() + 10 * 86400000).toISOString(),
        ordered_at: now,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'po_000099',
        restaurant_id: INITIAL_RESTAURANT_ID,
        order_number: 'OC-000099',
        supplier_id: 'sup_central_abastos',
        supplier_name: 'Central de Abarrotes y Verduras Don Pepe',
        status: 'received',
        items: [
          {
            id: 'poi_099_1',
            inventory_item_id: 'inv_pechuga_pollo',
            item_name: 'Pechuga de Pollo en Cubos',
            sku: 'POL-PECH-01',
            quantity_ordered: 15,
            quantity_received: 15,
            unit: 'kg',
            cost_cents_per_unit: 13000,
            total_cost_cents: 195000,
          },
        ],
        subtotal_cents: 195000,
        tax_cents: 0,
        total_cents: 195000,
        receipts: [
          {
            id: 'rec_seed_099_1',
            restaurant_id: INITIAL_RESTAURANT_ID,
            purchase_order_id: 'po_000099',
            receipt_number: 'REC-00002',
            invoice_number: 'REM-1092',
            invoice_date: now,
            received_by: 'Chef Ejecutivo',
            received_at: now,
            items: [
              {
                purchase_order_item_id: 'poi_099_1',
                inventory_item_id: 'inv_pechuga_pollo',
                item_name: 'Pechuga de Pollo en Cubos',
                quantity_received: 15,
                quantity_accepted: 15,
                quantity_rejected: 0,
                unit: 'kg',
                cost_cents_per_unit: 13000,
                conversion_factor: 1,
                base_unit: 'kg',
              },
            ],
            subtotal_cents: 195000,
            tax_cents: 0,
            total_cents: 195000,
            notes: 'Recibido completo en temperatura óptima.',
          },
        ],
        payment_status: 'paid',
        paid_amount_cents: 195000,
        ordered_at: now,
        created_at: now,
        updated_at: now,
      },
    ],
    price_history: [
      {
        id: 'ph_seed_1',
        restaurant_id: INITIAL_RESTAURANT_ID,
        inventory_item_id: 'inv_carne_angus',
        item_name: 'Carne Molida Angus 80/20',
        supplier_id: 'sup_carnes_norte',
        supplier_name: 'Distribuidora Carnes del Norte S.A. de C.V.',
        purchase_order_id: 'po_000095',
        receipt_id: 'rec_000001',
        quantity_received: 10,
        unit: 'kg',
        cost_cents_per_unit: 18000,
        cost_cents_per_base_unit: 18000,
        date: new Date(Date.now() - 7 * 86400000).toISOString(),
      },
      {
        id: 'ph_seed_2',
        restaurant_id: INITIAL_RESTAURANT_ID,
        inventory_item_id: 'inv_pan_burger',
        item_name: 'Pan Brioche para Hamburguesa',
        supplier_id: 'sup_panaderia_artesanal',
        supplier_name: 'Panadería Artesanal San Juan',
        purchase_order_id: 'po_000100',
        receipt_id: 'rec_seed_100_1',
        quantity_received: 6,
        unit: 'caja',
        cost_cents_per_unit: 19200,
        cost_cents_per_base_unit: 800,
        date: now,
      },
      {
        id: 'ph_seed_3',
        restaurant_id: INITIAL_RESTAURANT_ID,
        inventory_item_id: 'inv_pechuga_pollo',
        item_name: 'Pechuga de Pollo en Cubos',
        supplier_id: 'sup_central_abastos',
        supplier_name: 'Central de Abarrotes y Verduras Don Pepe',
        purchase_order_id: 'po_000099',
        receipt_id: 'rec_seed_099_1',
        quantity_received: 15,
        unit: 'kg',
        cost_cents_per_unit: 13000,
        cost_cents_per_base_unit: 13000,
        date: now,
      },
    ],
    users: [
      {
        id: 'usr_admin_01',
        email: 'roberto.gomez@directaurante.com',
        name: 'Roberto Gómez',
        phone: '+52 81 8300 0001',
        is_superadmin: true,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'usr_manager_01',
        email: 'mariana.t@directaurante.com',
        name: 'Mariana Torres',
        phone: '+52 81 8300 0002',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'usr_carlos_01',
        email: 'carlos.mendez@directaurante.com',
        name: 'Carlos Méndez',
        phone: '+52 81 8300 0003',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'usr_ana_01',
        email: 'ana.ruiz@directaurante.com',
        name: 'Ana Ruiz',
        phone: '+52 81 8300 0004',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'usr_chef_01',
        email: 'chef.luis@directaurante.com',
        name: 'Chef Luis Morales',
        phone: '+52 81 8300 0005',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'usr_juan_almacen',
        email: 'juan.perez@directaurante.com',
        name: 'Juan Pérez',
        phone: '+52 81 8300 0006',
        created_at: now,
        updated_at: now,
      },
    ],
    roles: [
      {
        id: 'role_owner',
        restaurant_id: INITIAL_RESTAURANT_ID,
        name: 'Propietario / Administrador',
        description: 'Acceso total a todas las operaciones, finanzas, personal y configuración del restaurante',
        permissions: [...ALL_PERMISSIONS],
        is_system: true,
        is_active: true,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'role_manager',
        restaurant_id: INITIAL_RESTAURANT_ID,
        name: 'Gerente / Encargado de Turno',
        description: 'Gestión operacional completa, comandas, mesas, personal, reportes y supervisión',
        permissions: [
          'restaurant.view',
          'orders.view',
          'orders.create',
          'orders.update',
          'orders.cancel',
          'tables.view',
          'tables.manage',
          'payments.view',
          'payments.create',
          'payments.refund',
          'cash.view',
          'cash.open',
          'cash.close',
          'cash.adjust',
          'expenses.view',
          'expenses.create',
          'expenses.edit',
          'financial.view',
          'reports.financial',
          'settlements.view',
          'settlements.manage',
          'inventory.view',
          'inventory.adjust',
          'recipes.view',
          'purchases.view',
          'purchases.create',
          'purchases.receive',
          'production.view',
          'production.create',
          'production.complete',
          'production.cancel',
          'production.waste',
          'staff.view',
          'staff.manage',
          'roles.view',
          'shifts.view',
          'shifts.manage',
          'shifts.start',
          'shifts.end',
          'reports.view',
        ],
        is_system: true,
        is_active: true,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'role_waiter',
        restaurant_id: INITIAL_RESTAURANT_ID,
        name: 'Mesero / Servicio de Salón',
        description: 'Atención en salón, comandas, servicio a mesas, comensales y registro de turno',
        permissions: [
          'orders.view',
          'orders.create',
          'orders.update',
          'tables.view',
          'tables.manage',
          'shifts.view',
          'shifts.start',
          'shifts.end',
        ],
        is_system: true,
        is_active: true,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'role_cashier',
        restaurant_id: INITIAL_RESTAURANT_ID,
        name: 'Cajero / Facturación',
        description: 'Control de caja registradora, cobro de cuentas globales/individuales y arqueos',
        permissions: [
          'orders.view',
          'payments.view',
          'payments.create',
          'payments.refund',
          'cash.view',
          'cash.open',
          'cash.close',
          'cash.adjust',
          'expenses.view',
          'expenses.create',
          'tables.view',
          'shifts.view',
          'shifts.start',
          'shifts.end',
          'reports.view',
        ],
        is_system: true,
        is_active: true,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'role_kitchen',
        restaurant_id: INITIAL_RESTAURANT_ID,
        name: 'Cocina / KDS',
        description: 'Preparación de comandas, órdenes de transformación/producción y recetas técnicas',
        permissions: [
          'orders.view',
          'production.view',
          'production.create',
          'production.complete',
          'production.cancel',
          'production.waste',
          'recipes.view',
          'inventory.view',
          'shifts.view',
          'shifts.start',
          'shifts.end',
        ],
        is_system: true,
        is_active: true,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'role_bar',
        restaurant_id: INITIAL_RESTAURANT_ID,
        name: 'Barra / Bartender',
        description: 'Servicio de barra, coctelería y preparación de bebidas',
        permissions: [
          'orders.view',
          'recipes.view',
          'shifts.view',
          'shifts.start',
          'shifts.end',
        ],
        is_system: true,
        is_active: true,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'role_inventory',
        restaurant_id: INITIAL_RESTAURANT_ID,
        name: 'Almacén y Kárdex',
        description: 'Existencias físicas, ajustes de inventario, conteos y catálogo de insumos',
        permissions: [
          'inventory.view',
          'inventory.adjust',
          'recipes.view',
          'shifts.view',
          'shifts.start',
          'shifts.end',
          'reports.view',
        ],
        is_system: true,
        is_active: true,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'role_purchasing',
        restaurant_id: INITIAL_RESTAURANT_ID,
        name: 'Compras y Proveedores',
        description: 'Órdenes de compra, recepción de mercancía y gestión de catálogo de proveedores',
        permissions: [
          'purchases.view',
          'purchases.create',
          'purchases.receive',
          'inventory.view',
          'shifts.view',
          'shifts.start',
          'shifts.end',
        ],
        is_system: true,
        is_active: true,
        created_at: now,
        updated_at: now,
      },
    ],
    restaurant_members: [
      {
        id: 'mem_admin_01',
        restaurant_id: INITIAL_RESTAURANT_ID,
        user_id: 'usr_admin_01',
        role_id: 'role_owner',
        display_name: 'Roberto Gómez (Admin)',
        employee_code: 'DIR-001',
        email: 'roberto.gomez@directaurante.com',
        phone: '+52 81 8300 0001',
        is_active: true,
        joined_at: '2026-01-01T08:00:00.000Z',
        notes: 'Fundador y Director General',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'mem_manager_01',
        restaurant_id: INITIAL_RESTAURANT_ID,
        user_id: 'usr_manager_01',
        role_id: 'role_manager',
        display_name: 'Mariana Torres (Gerente)',
        employee_code: 'DIR-002',
        email: 'mariana.t@directaurante.com',
        phone: '+52 81 8300 0002',
        is_active: true,
        joined_at: '2026-01-15T09:00:00.000Z',
        notes: 'Encargada de turno matutino y calidad',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'mem_carlos_01',
        restaurant_id: INITIAL_RESTAURANT_ID,
        user_id: 'usr_carlos_01',
        role_id: 'role_waiter',
        display_name: 'Carlos Méndez (Mesero)',
        employee_code: 'DIR-003',
        email: 'carlos.mendez@directaurante.com',
        phone: '+52 81 8300 0003',
        is_active: true,
        joined_at: '2026-02-01T11:00:00.000Z',
        notes: 'Capitán de meseros salón principal',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'mem_ana_01',
        restaurant_id: INITIAL_RESTAURANT_ID,
        user_id: 'usr_ana_01',
        role_id: 'role_cashier',
        display_name: 'Ana Ruiz (Cajera)',
        employee_code: 'DIR-004',
        email: 'ana.ruiz@directaurante.com',
        phone: '+52 81 8300 0004',
        is_active: true,
        joined_at: '2026-02-10T10:00:00.000Z',
        notes: 'Cajera principal turno vespertino',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'mem_chef_01',
        restaurant_id: INITIAL_RESTAURANT_ID,
        user_id: 'usr_chef_01',
        role_id: 'role_kitchen',
        display_name: 'Chef Luis Morales',
        employee_code: 'DIR-005',
        email: 'chef.luis@directaurante.com',
        phone: '+52 81 8300 0005',
        is_active: true,
        joined_at: '2026-01-10T07:00:00.000Z',
        notes: 'Chef ejecutivo / Jefe de cocina caliente',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'mem_juan_01',
        restaurant_id: INITIAL_RESTAURANT_ID,
        user_id: 'usr_juan_almacen',
        role_id: 'role_inventory',
        display_name: 'Juan Pérez (Almacén)',
        employee_code: 'DIR-006',
        email: 'juan.perez@directaurante.com',
        phone: '+52 81 8300 0006',
        is_active: true,
        joined_at: '2026-02-15T08:00:00.000Z',
        notes: 'Encargado de recepción y mermas',
        created_at: now,
        updated_at: now,
      },
    ],
    shifts: [
      {
        id: 'shf_seed_01',
        restaurant_id: INITIAL_RESTAURANT_ID,
        member_id: 'mem_carlos_01',
        user_id: 'usr_carlos_01',
        role_id: 'role_waiter',
        scheduled_start: '2026-10-05T12:00:00.000Z',
        scheduled_end: '2026-10-05T20:00:00.000Z',
        actual_start: new Date(Date.now() - 2.5 * 3600 * 1000).toISOString(),
        status: 'active',
        notes: 'Turno salón principal',
        created_by: 'usr_manager_01',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'shf_seed_02',
        restaurant_id: INITIAL_RESTAURANT_ID,
        member_id: 'mem_ana_01',
        user_id: 'usr_ana_01',
        role_id: 'role_cashier',
        scheduled_start: '2026-10-05T11:00:00.000Z',
        scheduled_end: '2026-10-05T19:00:00.000Z',
        actual_start: new Date(Date.now() - 3.5 * 3600 * 1000).toISOString(),
        status: 'active',
        cash_shift_id: 'shift_init_01',
        notes: 'Caja principal vinculada',
        created_by: 'usr_manager_01',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'shf_seed_03',
        restaurant_id: INITIAL_RESTAURANT_ID,
        member_id: 'mem_chef_01',
        user_id: 'usr_chef_01',
        role_id: 'role_kitchen',
        scheduled_start: '2026-10-05T07:00:00.000Z',
        scheduled_end: '2026-10-05T15:00:00.000Z',
        actual_start: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
        actual_end: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
        status: 'completed',
        notes: 'Producción matutina y mise en place',
        created_by: 'usr_manager_01',
        created_at: now,
        updated_at: now,
      },
    ],
    member_history: [
      {
        id: 'mh_seed_01',
        member_id: 'mem_admin_01',
        restaurant_id: INITIAL_RESTAURANT_ID,
        event_type: 'joined',
        new_role_id: 'role_owner',
        performed_by: 'usr_admin_01',
        notes: 'Membresía inicial de propietario',
        created_at: '2026-01-01T08:00:00.000Z',
      },
      {
        id: 'mh_seed_02',
        member_id: 'mem_manager_01',
        restaurant_id: INITIAL_RESTAURANT_ID,
        event_type: 'joined',
        new_role_id: 'role_manager',
        performed_by: 'usr_admin_01',
        notes: 'Alta como Gerente de Restaurante',
        created_at: '2026-01-15T09:00:00.000Z',
      },
      {
        id: 'mh_seed_03',
        member_id: 'mem_carlos_01',
        restaurant_id: INITIAL_RESTAURANT_ID,
        event_type: 'joined',
        new_role_id: 'role_waiter',
        performed_by: 'usr_manager_01',
        notes: 'Alta de personal de meseros',
        created_at: '2026-02-01T11:00:00.000Z',
      },
    ],
    customers: [
      {
        id: 'cust_carlos_01',
        name: 'Carlos Méndez',
        email: 'carlos.cliente@gmail.com',
        phone: '+52 81 1234 5678',
        birth_date: '1992-05-14',
        marketing_opt_in: true,
        marketing_updated_at: '2026-01-01T00:00:00.000Z',
        addresses: [
          {
            id: 'addr_carlos_1',
            street: 'Av. Eugenio Garza Sada',
            number: '2410',
            interior: 'Apto 4B',
            colony: 'Tecnológico',
            city: 'Monterrey',
            state: 'Nuevo León',
            postal_code: '64700',
            references: 'Torre Residencial, portón negro',
            label: 'home',
            is_default: true,
            created_at: '2026-01-01T00:00:00.000Z',
          },
        ],
        preferences: {
          allergies: [],
          favorite_items: ['prod_hamburguesa', 'prod_boneless'],
          dietary_notes: 'Prefiere aderezo aparte',
        },
        is_active: true,
        created_at: '2026-01-01T00:00:00.000Z',
        updated_at: now,
      },
      {
        id: 'cust_ana_01',
        name: 'Ana Sofía Garza',
        email: 'ana.sofia@gmail.com',
        phone: '+52 81 8765 4321',
        birth_date: '1995-11-20',
        marketing_opt_in: true,
        marketing_updated_at: '2026-02-01T00:00:00.000Z',
        addresses: [
          {
            id: 'addr_ana_1',
            street: 'Calzada del Valle',
            number: '400',
            colony: 'Del Valle',
            city: 'San Pedro Garza García',
            state: 'Nuevo León',
            postal_code: '66220',
            label: 'work',
            is_default: true,
            created_at: '2026-02-01T00:00:00.000Z',
          },
        ],
        preferences: {
          allergies: ['ing_cacahuate'],
          favorite_items: ['prod_ensalada'],
        },
        is_active: true,
        created_at: '2026-02-01T00:00:00.000Z',
        updated_at: now,
      },
      {
        id: 'cust_luis_01',
        name: 'Luis Fernando Rojas',
        email: 'luis.rojas@gmail.com',
        phone: '+52 81 5555 1234',
        marketing_opt_in: false,
        addresses: [],
        preferences: {
          favorite_items: ['prod_michelada'],
        },
        is_active: true,
        created_at: '2026-03-01T00:00:00.000Z',
        updated_at: now,
      },
    ],
    loyalty_accounts: [
      {
        id: 'loy_acc_carlos',
        restaurant_id: INITIAL_RESTAURANT_ID,
        customer_id: 'cust_carlos_01',
        points_balance: 850,
        lifetime_points: 1200,
        tier: 'gold',
        created_at: '2026-01-01T00:00:00.000Z',
        updated_at: now,
      },
      {
        id: 'loy_acc_ana',
        restaurant_id: INITIAL_RESTAURANT_ID,
        customer_id: 'cust_ana_01',
        points_balance: 320,
        lifetime_points: 450,
        tier: 'silver',
        created_at: '2026-02-01T00:00:00.000Z',
        updated_at: now,
      },
      {
        id: 'loy_acc_luis',
        restaurant_id: INITIAL_RESTAURANT_ID,
        customer_id: 'cust_luis_01',
        points_balance: 100,
        lifetime_points: 100,
        tier: 'bronze',
        created_at: '2026-03-01T00:00:00.000Z',
        updated_at: now,
      },
    ],
    loyalty_transactions: [
      {
        id: 'lt_seed_01',
        restaurant_id: INITIAL_RESTAURANT_ID,
        customer_id: 'cust_carlos_01',
        type: 'earn',
        points: 500,
        balance_before: 0,
        balance_after: 500,
        reference_type: 'order',
        reference_id: 'ord_init_100',
        description: 'Puntos acumulados por consumo en comanda',
        created_at: '2026-01-15T14:00:00.000Z',
        created_by: 'System',
      },
      {
        id: 'lt_seed_02',
        restaurant_id: INITIAL_RESTAURANT_ID,
        customer_id: 'cust_carlos_01',
        type: 'earn',
        points: 350,
        balance_before: 500,
        balance_after: 850,
        reference_type: 'order',
        reference_id: 'ord_init_101',
        description: 'Puntos acumulados por consumo de alimentos',
        created_at: '2026-02-10T16:00:00.000Z',
        created_by: 'System',
      },
      {
        id: 'lt_seed_03',
        restaurant_id: INITIAL_RESTAURANT_ID,
        customer_id: 'cust_ana_01',
        type: 'earn',
        points: 320,
        balance_before: 0,
        balance_after: 320,
        reference_type: 'order',
        reference_id: 'ord_init_102',
        description: 'Puntos por consumo en restaurante',
        created_at: '2026-02-15T13:00:00.000Z',
        created_by: 'System',
      },
    ],
    loyalty_rewards: [
      {
        id: 'rew_descuento_50',
        restaurant_id: INITIAL_RESTAURANT_ID,
        name: 'Descuento de $50 MXN',
        description: 'Aplica $50.00 de descuento directo en tu cuenta total',
        reward_type: 'discount_amount',
        value: 5000,
        points_required: 500,
        is_active: true,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'rew_refresco_gratis',
        restaurant_id: INITIAL_RESTAURANT_ID,
        name: 'Refresco o Bebida Gratis',
        description: 'Canjea por una bebida sin alcohol de cortesía en tu consumo',
        reward_type: 'free_product',
        value: 3500,
        points_required: 250,
        is_active: true,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'rew_postre_gratis',
        restaurant_id: INITIAL_RESTAURANT_ID,
        name: 'Postre de la Casa (15% Desc)',
        description: '15% de descuento en el total de platillos dulces',
        reward_type: 'discount_percent',
        value: 15,
        points_required: 400,
        is_active: true,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'rew_descuento_100',
        restaurant_id: INITIAL_RESTAURANT_ID,
        name: 'Descuento VIP de $100 MXN',
        description: 'Aplica $100.00 de descuento en consumos mayores a $300',
        reward_type: 'discount_amount',
        value: 10000,
        points_required: 900,
        is_active: true,
        created_at: now,
        updated_at: now,
      },
    ],
    promotions: [
      {
        id: 'promo_bienvenida',
        restaurant_id: INITIAL_RESTAURANT_ID,
        name: 'Bienvenida 15% OFF',
        description: '15% de descuento en tu primera comanda ingresando el cupón BIENVENIDO',
        type: 'coupon',
        discount_percent: 15,
        coupon_code: 'BIENVENIDO',
        min_order_cents: 20000,
        max_discount_cents: 10000,
        max_uses_total: 1000,
        max_uses_per_customer: 1,
        current_uses_count: 5,
        start_date: '2026-01-01T00:00:00.000Z',
        end_date: '2026-12-31T23:59:59.000Z',
        is_active: true,
        stackable_with_loyalty: false,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'promo_burger_day',
        restaurant_id: INITIAL_RESTAURANT_ID,
        name: 'Burger Fest -$50 MXN',
        description: '$50 MXN de descuento en consumo mínimo de $250 MXN con cupón BURGER50',
        type: 'fixed_amount',
        discount_amount_cents: 5000,
        coupon_code: 'BURGER50',
        min_order_cents: 25000,
        max_uses_total: 500,
        max_uses_per_customer: 2,
        current_uses_count: 12,
        is_active: true,
        stackable_with_loyalty: false,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'promo_2x1_cerveza',
        restaurant_id: INITIAL_RESTAURANT_ID,
        name: 'Jueves Cervecero 20% OFF',
        description: '20% de descuento en bebidas seleccionadas de barra',
        type: 'percentage',
        discount_percent: 20,
        coupon_code: 'JUEVES20',
        min_order_cents: 10000,
        current_uses_count: 8,
        is_active: true,
        stackable_with_loyalty: true,
        created_at: now,
        updated_at: now,
      },
    ],
    promotion_redemptions: [
      {
        id: 'pr_seed_01',
        restaurant_id: INITIAL_RESTAURANT_ID,
        promotion_id: 'promo_burger_day',
        customer_id: 'cust_carlos_01',
        order_id: 'ord_init_100',
        coupon_code: 'BURGER50',
        discount_applied_cents: 5000,
        redeemed_at: '2026-01-15T14:00:00.000Z',
      },
    ],
    expenses: [
      {
        id: 'exp_init_01',
        restaurant_id: INITIAL_RESTAURANT_ID,
        category: 'supplies',
        amount_cents: 15000,
        currency: 'MXN',
        payment_method: 'cash',
        vendor: 'Hielo Cristalino S.A.',
        reference: 'T-1029',
        description: 'Bolsa de hielo purificado 15kg para barra',
        status: 'paid',
        cash_session_id: 'shift_init_01',
        created_by: 'Cajero Principal',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'exp_init_02',
        restaurant_id: INITIAL_RESTAURANT_ID,
        category: 'utilities',
        amount_cents: 450000,
        currency: 'MXN',
        payment_method: 'transfer',
        vendor: 'CFE Suministrador de Servicios Básicos',
        reference: 'CFE-REC-8910',
        description: 'Servicio de energía eléctrica local comercial mes anterior',
        status: 'paid',
        created_by: 'Gerente / Encargado',
        created_at: now,
        updated_at: now,
      },
    ],
    financial_movements: [
      {
        id: 'fin_init_01',
        restaurant_id: INITIAL_RESTAURANT_ID,
        type: 'opening',
        direction: 'in',
        amount_cents: 200000,
        currency: 'MXN',
        payment_method: 'cash',
        reference_type: 'cash_session',
        reference_id: 'shift_init_01',
        cash_session_id: 'shift_init_01',
        description: 'Fondo de apertura de turno inicial',
        created_by: 'Cajero Principal (Admin)',
        created_at: now,
      },
      {
        id: 'fin_init_02',
        restaurant_id: INITIAL_RESTAURANT_ID,
        type: 'expense',
        direction: 'out',
        amount_cents: 15000,
        currency: 'MXN',
        payment_method: 'cash',
        reference_type: 'expense',
        reference_id: 'exp_init_01',
        cash_session_id: 'shift_init_01',
        description: 'Gasto operativo: Bolsa de hielo purificado 15kg para barra',
        created_by: 'Cajero Principal',
        created_at: now,
      },
      {
        id: 'fin_init_03',
        restaurant_id: INITIAL_RESTAURANT_ID,
        type: 'expense',
        direction: 'out',
        amount_cents: 450000,
        currency: 'MXN',
        payment_method: 'transfer',
        reference_type: 'expense',
        reference_id: 'exp_init_02',
        description: 'Gasto operativo: Servicio de energía eléctrica CFE',
        created_by: 'Gerente / Encargado',
        created_at: now,
      },
    ],
    restaurant_settlements: [
      {
        id: 'set_rest_01',
        restaurant_id: INITIAL_RESTAURANT_ID,
        channel: 'directgo',
        period_start: '2026-01-01T00:00:00.000Z',
        period_end: '2026-01-15T23:59:59.000Z',
        gross_sales_cents: 850000,
        commissions_cents: 85000,
        net_payout_cents: 765000,
        status: 'settled',
        payment_reference: 'TRANS-SPEI-99120',
        created_by: 'Directaurante Finance Core',
        settled_at: now,
        created_at: now,
      },
    ],
    driver_settlements: [
      {
        id: 'set_drv_01',
        restaurant_id: INITIAL_RESTAURANT_ID,
        driver_id: 'drv_pedro_01',
        driver_name: 'Pedro Repartidor',
        period_date: '2026-01-15',
        cash_collected_cents: 45000,
        delivery_fees_earned_cents: 12000,
        tips_cents: 5000,
        balance_due_cents: 28000,
        status: 'reconciled',
        created_by: 'Cajero Principal',
        reconciled_at: now,
        created_at: now,
      },
    ],
    solutions: [
      {
        solution_id: 'delivery',
        name: 'Delivery & Despacho',
        description: 'Gestión de órdenes de reparto, asignación de repartidores y cobro contra entrega.',
        version: '1.0.0',
        status: 'active',
        category: 'logistics',
        dependencies: [],
        capabilities: [
          {
            id: 'delivery.orders',
            name: 'Órdenes de Reparto',
            description: 'Creación y seguimiento de pedidos para entrega a domicilio',
            solution_id: 'delivery',
            required_permissions: ['orders.view', 'orders.create'],
          },
          {
            id: 'delivery.dispatch',
            name: 'Despacho de Pedidos',
            description: 'Asignación de comanda a repartidor propio o externo',
            solution_id: 'delivery',
            required_permissions: ['orders.update'],
          },
          {
            id: 'delivery.driver_tracking',
            name: 'Rastreo de Repartidor',
            description: 'Monitoreo de tiempos y estado en ruta',
            solution_id: 'delivery',
            required_permissions: ['orders.view'],
          },
          {
            id: 'delivery.payment_receipts',
            name: 'Cobro y Comprobantes de Entrega',
            description: 'Liquidación de efectivo y comprobantes de reparto',
            solution_id: 'delivery',
            required_permissions: ['payments.create'],
          },
        ],
        required_permissions: ['orders.view', 'orders.create', 'orders.update', 'payments.create'],
        commercial_availability: 'available',
        icon: 'Truck',
      },
      {
        solution_id: 'pos',
        name: 'DirectPost / POS Core',
        description: 'Control de punto de venta físico: salones, mesas, comandero táctil, división de cuentas y turnos de caja.',
        version: '1.0.0',
        status: 'active',
        category: 'operations',
        dependencies: [],
        capabilities: [
          {
            id: 'pos.tables',
            name: 'Mapa de Mesas',
            description: 'Gestión gráfica de salones y ocupación de mesas',
            solution_id: 'pos',
            required_permissions: ['tables.view', 'tables.manage'],
          },
          {
            id: 'pos.orders',
            name: 'Comandero de Salón',
            description: 'Toma rápida de comandas en sala y barra',
            solution_id: 'pos',
            required_permissions: ['orders.create', 'orders.view'],
          },
          {
            id: 'pos.split_payment',
            name: 'Pago Dividido',
            description: 'Cuentas separadas por comensal o montos parciales',
            solution_id: 'pos',
            required_permissions: ['payments.create'],
          },
          {
            id: 'pos.cash_shift',
            name: 'Arqueo y Turnos de Caja',
            description: 'Apertura con fondo, movimientos de efectivo y corte ciego',
            solution_id: 'pos',
            required_permissions: ['cash.open', 'cash.close', 'cash.view'],
          },
          {
            id: 'pos.subaccounts',
            name: 'Subcuentas por Comensal',
            description: 'Cuentas independientes por asiento con consolidación',
            solution_id: 'pos',
            required_permissions: ['orders.update'],
          },
        ],
        required_permissions: ['tables.view', 'tables.manage', 'orders.create', 'payments.create', 'cash.view'],
        commercial_availability: 'available',
        icon: 'UtensilsCrossed',
      },
      {
        solution_id: 'directprint',
        name: 'DirectPrint ESC/POS',
        description: 'Infraestructura de impresión térmica local o en la nube para comandas, cocina, barra y pre-cuenta.',
        version: '1.0.0',
        status: 'active',
        category: 'hardware',
        dependencies: [],
        capabilities: [
          {
            id: 'print.order',
            name: 'Impresión de Comanda',
            description: 'Emisión de ticket general de comanda',
            solution_id: 'directprint',
            required_permissions: ['orders.view'],
          },
          {
            id: 'print.kitchen_ticket',
            name: 'Ticket de Cocina',
            description: 'Ruteo de platillos a impresora de cocina caliente/fría (58/80mm)',
            solution_id: 'directprint',
            required_permissions: ['orders.view'],
          },
          {
            id: 'print.cashier_ticket',
            name: 'Ticket de Caja y Pre-cuenta',
            description: 'Emisión de pre-cuenta y recibo oficial de cobro',
            solution_id: 'directprint',
            required_permissions: ['payments.view'],
          },
          {
            id: 'print.reprint',
            name: 'Reimpresión Segura',
            description: 'Duplicado trazable de comandas anteriores',
            solution_id: 'directprint',
            required_permissions: ['orders.view'],
          },
          {
            id: 'print.station_management',
            name: 'Gestión de Estaciones',
            description: 'Configuración de impresoras térmicas ESC/POS por estación',
            solution_id: 'directprint',
            required_permissions: ['restaurant.manage'],
          },
        ],
        required_permissions: ['orders.view'],
        commercial_availability: 'available',
        icon: 'Printer',
      },
      {
        solution_id: 'loyalty',
        name: 'DirectLoyalty Club',
        description: 'Programa de fidelización de comensales con acumulación de puntos, catálogo de recompensas y niveles.',
        version: '1.0.0',
        status: 'active',
        category: 'growth',
        dependencies: [],
        capabilities: [
          {
            id: 'loyalty.points',
            name: 'Acumulación de Puntos',
            description: 'Emisión automática de puntos por consumo en restaurante',
            solution_id: 'loyalty',
            required_permissions: ['loyalty.view'],
          },
          {
            id: 'loyalty.rewards',
            name: 'Catálogo de Recompensas',
            description: 'Premios, bebidas de cortesía y descuentos canjeables',
            solution_id: 'loyalty',
            required_permissions: ['loyalty.view', 'loyalty.manage'],
          },
          {
            id: 'loyalty.tiers',
            name: 'Niveles de Lealtad',
            description: 'Clasificación por consumo (Bronze, Silver, Gold, Platinum)',
            solution_id: 'loyalty',
            required_permissions: ['loyalty.view'],
          },
          {
            id: 'loyalty.redemption',
            name: 'Canje de Puntos',
            description: 'Aplicación segura e inmutable de recompensas a la cuenta',
            solution_id: 'loyalty',
            required_permissions: ['loyalty.manage'],
          },
        ],
        required_permissions: ['loyalty.view', 'loyalty.manage'],
        commercial_availability: 'available',
        icon: 'Award',
      },
      {
        solution_id: 'crm',
        name: 'DirectCRM & Promociones',
        description: 'Gestión de perfiles de clientes, alergias, historial de consumo, segmentación y motor de cupones.',
        version: '1.0.0',
        status: 'active',
        category: 'growth',
        dependencies: [],
        capabilities: [
          {
            id: 'crm.profiles',
            name: 'Directorio de Clientes',
            description: 'Fichas de clientes con gustos, alergias y datos de contacto',
            solution_id: 'crm',
            required_permissions: ['customers.view'],
          },
          {
            id: 'crm.segments',
            name: 'Segmentación Inteligente',
            description: 'Filtros de clientes VIP, frecuentes y en riesgo',
            solution_id: 'crm',
            required_permissions: ['customers.view'],
          },
          {
            id: 'crm.promotions',
            name: 'Motor de Promociones',
            description: 'Reglas de descuento porcentual, monto fijo y consumo mínimo',
            solution_id: 'crm',
            required_permissions: ['promotions.view', 'promotions.manage'],
          },
          {
            id: 'crm.coupons',
            name: 'Cupones de Descuento',
            description: 'Códigos promocionales con control de vigencia y redención',
            solution_id: 'crm',
            required_permissions: ['promotions.manage'],
          },
        ],
        required_permissions: ['customers.view', 'promotions.view', 'promotions.manage'],
        commercial_availability: 'available',
        icon: 'Sparkles',
      },
      {
        solution_id: 'kds',
        name: 'Kitchen Display System (KDS)',
        description: 'Pantalla de preparación en tiempo real para cocineros y pase con tiempos SLA y estados atómicos.',
        version: '1.0.0',
        status: 'active',
        category: 'kitchen',
        dependencies: ['pos'],
        capabilities: [
          {
            id: 'kds.kitchen_display',
            name: 'Pantalla de Cocina',
            description: 'Visualización de comandas activas por orden de llegada',
            solution_id: 'kds',
            required_permissions: ['orders.view'],
          },
          {
            id: 'kds.station_routing',
            name: 'Ruteo por Estación',
            description: 'Filtrado de platillos por estación caliente, fría o barra',
            solution_id: 'kds',
            required_permissions: ['orders.view'],
          },
          {
            id: 'kds.expediter',
            name: 'Control de Pase / Despacho',
            description: 'Revisión final de platillos antes de entrega a mesa',
            solution_id: 'kds',
            required_permissions: ['orders.update'],
          },
          {
            id: 'kds.timing',
            name: 'Semáforos SLA',
            description: 'Control de minutos transcurridos y alertas de demora',
            solution_id: 'kds',
            required_permissions: ['orders.view'],
          },
        ],
        required_permissions: ['orders.view', 'orders.update'],
        commercial_availability: 'available',
        icon: 'ChefHat',
      },
      {
        solution_id: 'analytics',
        name: 'DirectAnalytics & P&L',
        description: 'Inteligencia operativa y financiera: Ventas netas, cálculo de COGS con escandallos, margen bruto y P&L.',
        version: '1.0.0',
        status: 'active',
        category: 'intelligence',
        dependencies: [],
        capabilities: [
          {
            id: 'analytics.sales',
            name: 'Analítica de Ventas',
            description: 'Ventas por hora, platillo estrella y métodos de pago',
            solution_id: 'analytics',
            required_permissions: ['reports.view'],
          },
          {
            id: 'analytics.pnl',
            name: 'Estado de Resultados P&L',
            description: 'Cálculo de utilidad neta descontando COGS y gastos operativos',
            solution_id: 'analytics',
            required_permissions: ['financial.view', 'reports.financial'],
          },
          {
            id: 'analytics.cogs',
            name: 'Control de COGS',
            description: 'Auditoría del costo real de ingredientes de recetas',
            solution_id: 'analytics',
            required_permissions: ['reports.financial'],
          },
          {
            id: 'analytics.inventory',
            name: 'Valoración de Inventario',
            description: 'Valor total de almacén y mermas registradas',
            solution_id: 'analytics',
            required_permissions: ['reports.view'],
          },
        ],
        required_permissions: ['financial.view', 'reports.financial', 'reports.view'],
        commercial_availability: 'available',
        icon: 'TrendingUp',
      },
    ],
    commercial_plans: [
      {
        id: 'plan_basic',
        name: 'Plan Básico (Delivery)',
        code: 'BASIC',
        description: 'Módulo esencial de entrega y pedidos para dark kitchens o delivery exclusivo.',
        tier: 'basic',
        solutions: ['delivery'],
        included_capabilities: ['delivery.orders', 'delivery.dispatch', 'delivery.driver_tracking', 'delivery.payment_receipts'],
        is_active: true,
        price_cents_monthly: 49900,
        currency: 'MXN',
        created_at: now,
      },
      {
        id: 'plan_pro',
        name: 'Plan Pro (Salón & Delivery)',
        code: 'PRO',
        description: 'Operación completa de punto de venta físico, pantalla KDS de cocina y programa de fidelidad.',
        tier: 'pro',
        solutions: ['delivery', 'pos', 'loyalty', 'kds'],
        included_capabilities: ['*'],
        is_active: true,
        price_cents_monthly: 129900,
        currency: 'MXN',
        created_at: now,
      },
      {
        id: 'plan_enterprise',
        name: 'Plan Enterprise / Suite Total',
        code: 'ENTERPRISE',
        description: 'Plataforma unificada completa con hardware térmico DirectPrint, CRM avanzado y analítica de P&L.',
        tier: 'enterprise',
        solutions: ['delivery', 'pos', 'directprint', 'loyalty', 'crm', 'kds', 'analytics'],
        included_capabilities: ['*'],
        is_active: true,
        price_cents_monthly: 249900,
        currency: 'MXN',
        created_at: now,
      },
    ],
    entitlements: [
      {
        id: 'ent_init_deliv',
        restaurant_id: INITIAL_RESTAURANT_ID,
        solution_id: 'delivery',
        capability: '*',
        status: 'active',
        source: 'plan',
        plan_id: 'plan_enterprise',
        start_date: now,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'ent_init_pos',
        restaurant_id: INITIAL_RESTAURANT_ID,
        solution_id: 'pos',
        capability: '*',
        status: 'active',
        source: 'plan',
        plan_id: 'plan_enterprise',
        start_date: now,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'ent_init_print',
        restaurant_id: INITIAL_RESTAURANT_ID,
        solution_id: 'directprint',
        capability: '*',
        status: 'active',
        source: 'plan',
        plan_id: 'plan_enterprise',
        start_date: now,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'ent_init_loyalty',
        restaurant_id: INITIAL_RESTAURANT_ID,
        solution_id: 'loyalty',
        capability: '*',
        status: 'active',
        source: 'plan',
        plan_id: 'plan_enterprise',
        start_date: now,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'ent_init_crm',
        restaurant_id: INITIAL_RESTAURANT_ID,
        solution_id: 'crm',
        capability: '*',
        status: 'active',
        source: 'plan',
        plan_id: 'plan_enterprise',
        start_date: now,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'ent_init_kds',
        restaurant_id: INITIAL_RESTAURANT_ID,
        solution_id: 'kds',
        capability: '*',
        status: 'active',
        source: 'plan',
        plan_id: 'plan_enterprise',
        start_date: now,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'ent_init_analytics',
        restaurant_id: INITIAL_RESTAURANT_ID,
        solution_id: 'analytics',
        capability: '*',
        status: 'active',
        source: 'plan',
        plan_id: 'plan_enterprise',
        start_date: now,
        created_at: now,
        updated_at: now,
      },
    ],
  };
}

class DatabaseManager {
  private data: DatabaseSchema;
  private saveTimeout: NodeJS.Timeout | null = null;

  constructor() {
    this.data = this.loadData();
  }

  private loadData(): DatabaseSchema {
    try {
      if (!fs.existsSync(DATA_DIR)) {
        fs.mkdirSync(DATA_DIR, { recursive: true });
      }
      if (fs.existsSync(DATA_FILE)) {
        const fileContent = fs.readFileSync(DATA_FILE, 'utf-8');
        const parsed = JSON.parse(fileContent);
        const defaultData = getDefaultSeedData();
        const mergedProducts = (parsed.products && parsed.products.length > 0 ? parsed.products : defaultData.products).map((p: any) => {
          const defP = defaultData.products.find(dp => dp.id === p.id);
          return {
            ...p,
            inventory_item_id: p.inventory_item_id || defP?.inventory_item_id,
          };
        });

        // Ensure newly added default inventory items exist in store
        const existingInventoryItems = parsed.inventory_items && parsed.inventory_items.length > 0
          ? parsed.inventory_items
          : defaultData.inventory_items;
        const missingInventoryItems = defaultData.inventory_items.filter(
          (di) => !existingInventoryItems.some((ei: any) => ei.id === di.id)
        );
        const mergedInventoryItems = [...existingInventoryItems, ...missingInventoryItems];

        // Ensure recipes exist
        const mergedRecipes = parsed.recipes && parsed.recipes.length > 0 ? parsed.recipes : defaultData.recipes;

        // Ensure suppliers exist
        const mergedSuppliers = parsed.suppliers && parsed.suppliers.length > 0 ? parsed.suppliers : defaultData.suppliers;

        // Ensure purchase orders exist
        const mergedPurchaseOrders = parsed.purchase_orders && parsed.purchase_orders.length > 0 ? parsed.purchase_orders : defaultData.purchase_orders;

        // Ensure price history exists
        const mergedPriceHistory = parsed.price_history && parsed.price_history.length > 0 ? parsed.price_history : defaultData.price_history;

        // Ensure users exist
        const mergedUsers = parsed.users && parsed.users.length > 0 ? parsed.users : defaultData.users;

        // Ensure roles exist
        const mergedRoles = parsed.roles && parsed.roles.length > 0 ? parsed.roles : defaultData.roles;

        // Ensure restaurant members exist
        const mergedMembers = parsed.restaurant_members && parsed.restaurant_members.length > 0 ? parsed.restaurant_members : defaultData.restaurant_members;

        // Ensure shifts exist
        const mergedShifts = parsed.shifts && parsed.shifts.length > 0 ? parsed.shifts : defaultData.shifts;

        // Ensure member history exists
        const mergedMemberHistory = parsed.member_history && parsed.member_history.length > 0 ? parsed.member_history : defaultData.member_history;

        // Ensure customers exist
        const mergedCustomers = parsed.customers && parsed.customers.length > 0 ? parsed.customers : defaultData.customers;

        // Ensure loyalty accounts exist
        const mergedLoyaltyAccounts = parsed.loyalty_accounts && parsed.loyalty_accounts.length > 0 ? parsed.loyalty_accounts : defaultData.loyalty_accounts;

        // Ensure loyalty transactions exist
        const mergedLoyaltyTransactions = parsed.loyalty_transactions && parsed.loyalty_transactions.length > 0 ? parsed.loyalty_transactions : defaultData.loyalty_transactions;

        // Ensure loyalty rewards exist
        const mergedLoyaltyRewards = parsed.loyalty_rewards && parsed.loyalty_rewards.length > 0 ? parsed.loyalty_rewards : defaultData.loyalty_rewards;

        // Ensure promotions exist
        const mergedPromotions = parsed.promotions && parsed.promotions.length > 0 ? parsed.promotions : defaultData.promotions;

        // Ensure promotion redemptions exist
        const mergedPromotionRedemptions = parsed.promotion_redemptions && parsed.promotion_redemptions.length > 0 ? parsed.promotion_redemptions : defaultData.promotion_redemptions;

        return {
          ...defaultData,
          ...parsed,
          products: mergedProducts,
          inventory_items: mergedInventoryItems,
          inventory_movements:
            parsed.inventory_movements && parsed.inventory_movements.length > 0
              ? parsed.inventory_movements
              : defaultData.inventory_movements,
          inventory_counts: parsed.inventory_counts || [],
          recipes: mergedRecipes,
          suppliers: mergedSuppliers,
          purchase_orders: mergedPurchaseOrders,
          price_history: mergedPriceHistory,
          users: mergedUsers,
          roles: mergedRoles,
          restaurant_members: mergedMembers,
          shifts: mergedShifts,
          member_history: mergedMemberHistory,
          customers: mergedCustomers,
          loyalty_accounts: mergedLoyaltyAccounts,
          loyalty_transactions: mergedLoyaltyTransactions,
          loyalty_rewards: mergedLoyaltyRewards,
          promotions: mergedPromotions,
          promotion_redemptions: mergedPromotionRedemptions,
          table_sessions: parsed.table_sessions || [],
          guest_subaccounts: parsed.guest_subaccounts || [],
          orders: parsed.orders || [],
          order_items: parsed.order_items || [],
          payments: parsed.payments || [],
          cash_shifts: parsed.cash_shifts || defaultData.cash_shifts,
          cash_movements: parsed.cash_movements || defaultData.cash_movements,
          audit_logs: parsed.audit_logs || defaultData.audit_logs,
          restaurant_plugins: parsed.restaurant_plugins || defaultData.restaurant_plugins,
          expenses: parsed.expenses && parsed.expenses.length > 0 ? parsed.expenses : defaultData.expenses,
          financial_movements:
            parsed.financial_movements && parsed.financial_movements.length > 0
              ? parsed.financial_movements
              : defaultData.financial_movements,
          restaurant_settlements:
            parsed.restaurant_settlements && parsed.restaurant_settlements.length > 0
              ? parsed.restaurant_settlements
              : defaultData.restaurant_settlements,
          driver_settlements:
            parsed.driver_settlements && parsed.driver_settlements.length > 0
              ? parsed.driver_settlements
              : defaultData.driver_settlements,
          solutions:
            parsed.solutions && parsed.solutions.length > 0
              ? parsed.solutions
              : defaultData.solutions,
          commercial_plans:
            parsed.commercial_plans && parsed.commercial_plans.length > 0
              ? parsed.commercial_plans
              : defaultData.commercial_plans,
          entitlements:
            parsed.entitlements && parsed.entitlements.length > 0
              ? parsed.entitlements
              : defaultData.entitlements,
        };
      }
    } catch (err) {
      console.warn('[DatabaseManager] Error reading persistent store, seeding default:', err);
    }
    const initial = getDefaultSeedData();
    this.persistSync(initial);
    return initial;
  }

  private persistSync(data: DatabaseSchema): void {
    try {
      if (!fs.existsSync(DATA_DIR)) {
        fs.mkdirSync(DATA_DIR, { recursive: true });
      }
      const tmpPath = `${DATA_FILE}.tmp.${Date.now()}`;
      fs.writeFileSync(tmpPath, JSON.stringify(data, null, 2), 'utf-8');
      fs.renameSync(tmpPath, DATA_FILE);
    } catch (err) {
      console.error('[DatabaseManager] Failed to persist data to disk:', err);
    }
  }

  public save(): void {
    if (this.saveTimeout) {
      clearTimeout(this.saveTimeout);
    }
    this.saveTimeout = setTimeout(() => {
      this.persistSync(this.data);
      this.saveTimeout = null;
    }, 50);
  }

  public get<K extends keyof DatabaseSchema>(collection: K): DatabaseSchema[K] {
    return this.data[collection];
  }

  public resetToDefault(): void {
    this.data = getDefaultSeedData();
    this.persistSync(this.data);
  }
}

export const db = new DatabaseManager();
export const DEFAULT_RESTAURANT_ID = INITIAL_RESTAURANT_ID;
